name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for Xcode
      id: check_xcode
      run: |
        if command -v xcodebuild &> /dev/null; then
          echo "has_xcode=true" >> $GITHUB_OUTPUT
        else
          echo "has_xcode=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Run tests (with Xcode)
      if: steps.check_xcode.outputs.has_xcode == 'true'
      run: npm test
      env:
        NODE_ENV: test
    
    - name: Run tests (without Xcode)
      if: steps.check_xcode.outputs.has_xcode == 'false'
      run: npm test
      env:
        NODE_ENV: test
        SKIP_XCODE_TESTS: true
    
    - name: Run linter (if available)
      run: npm run lint --if-present
      continue-on-error: true